image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - johnpapa.angular-essentials@0.6.3
    - bierner.github-markdown-preview@0.0.2
    - 2gua.rainbow-brackets@0.0.6
    - WakaTime.vscode-wakatime@2.2.1
    - asvetliakov.vscode-neovim@0.0.49
    - eamodio.gitlens@10.2.0

    - genuitecllc.codetogether@2.1.1

    - humao.rest-client@0.24.2

tasks:
  - before: printf "\n[settings]\napi_key = $WAKA_TIME_API_KEY\n" > ~/.wakatime.cfg
    init: npm install
    command: zsh